"""
BIG LIST OF STOPWORDS
"""

stopwords_redux = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you',
                   "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself',
                   'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her',
                   'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them',
                   'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom',
                   'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are',
                   'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had',
                   'having', 'do', 'does', 'did', 'doing', 'an', 'the',
                   'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while',
                   'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between',
                   'into', 'through', 'during', 'before', 'after', 'above', 'below',
                   'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under',
                   'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where',
                   'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most',
                   'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same',
                   'so', 'than', 'too', 'very', 'can', 'will', 'just', 'don',
                   "don't", 'should', "should've", 'now', 'll', 're', 've',
                   'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't",
                   'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't",
                   'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn',
                   "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't",
                   "'", 'abov', 'ani', 'becaus', 'befor', 'displaystyl', 'doe', 'dure', 'ha', 
                   'hi', 'onc', 'onli', 'ourselv', 's', 'subequ', 't', 'textnorm', 'themselv', 
                   'thi', 'underlin', 'veri', 'wa', 'whi', 'yourselv',
                   'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't", "mathrm", "mathbf", "left", "right",
                   "textrm", "textsf", "texttt", "textup", "textsl", "emph", "underline", "textit", "textmd", "textbf", "textsc", "textnormal",
                   "phantom", "align",  "subequations", "begin", "end", "displaystyle"
                   ]

added_stopwords = [
    'fathers', 'presently', 'bonding', 'seconds', 'played', 'stood',
    'fleets', 'ensured', 'faced', 'executed', 'assisted', 'contributed',
    'compose', 'motion', 'port', 'possesses', 'hot', 'weekend', 'add',
    'closing', 'expectations', 'auditing', 'close', 'fixed', 'choose',
    'stored', 'improved', 'permanent', 'additional', 'li', 'br', 'h1', 'h2', 'h3', 'span',
    'strong',
    'contact', 'feed', 'improvement', 'title', 'addition', 'pvt',
    'ltd', 'award', 'isolate', 'promise', 'exist', 'friendly', 'dj',
    'attitude', 'positive', 'good', 'explore', 'inconsistency',
    'clock', 'weakness', 'vulnerable', 'limited', 'complimentary',
    'compound', 'professional', 'synopsis', 'achievement',
    'moving', 'individual', 'ideal', 'level', 'capable',
    'bangalore', 'successfully', 'efforts', 'huge', 'strengths',
    'click', 'diligent', 'opinion', 'inexpensively', 'stating', 'serious',
    'aiming', '\xa0', 'altogether', 'confirmed', 'unconfirmed', 'merely',
    'updating', 'limiting', 'combination', 'experience', 'implement', 'mindset',
    'strive', 'ability', 'boxing', 'specialising', 'adapt', 'exploring', 'sustain',
    'putting', 'university', 'positive', 'attitude', 'employee', 'bengaluru',
    'pune', 'summary', 'working', 'inducted', 'appreciated', 'weaknesses', 'strengths',
    'exploring', 'case', 'participating', 'participated', 'approach', 'project title',
    'dump', 'requirements', 'education', 'process', 'takes', 'occasions', 'striving',
    'consolidated', 'performer', 'objective', 'volunteering', 'young', 'oriented',
    'school', 'certificate', 'family', 'adding', 'aim', 'difficult', 'easy', 'involved',
    'features', 'sex', 'application', 'features', 'college', 'multiple',
    'calls', 'skillset', 'appraisals', 'leaves', 'passport', 'valid', 'ill',
    'compromising', 'believes', 'belief', 'weekends', 'remain', 'familiar', 'finding',
    'skilled', 'languages', 'pressure', 'tasks', 'making', 'worked', 'processes',
    'english', 'scoring', 'won', 'competitions', 'playing', 'tennis', 'cricket', 'football',
    'guitar', 'piano', 'violin', 'individuals', 'spectrum placement', 'spectrum', 'placement',
    'academic', 'achievements', 'road', 'class', 'companies', 'saved', 'sorts', 'calculated',
    'totally', 'dimensions', 'late', 'introduction', 'nagar', 'affiliated', 'learn',
    'rewared', 'analyze', 'analyse', 'role', 'relocating', 'physically', 'challenged', 'town',
    'true', 'carried', 'street', 'race', 'cart', 'item', 'doesn', 'handles', 'carries',
    'payoff', 'expiry', 'instantly', 'filtering', 'drill', 'graduated', 'basically', 'deals',
    'single', 'unmarried', 'divorced', 'widowed', 'request', 'weekly', 'hindi', 'high', 'low',
    'medium', 'crore', 'linkedin', 'quizzes', 'easier', 'encompassing', 'enable', 'maximum',
    'bring', 'gandhi', 'learnings', 'recommended', 'propose', 'completion', 'dedicated',
    'appreciation', 'aimed', 'cultural', 'fest', 'mother', 'father', 'timely', 'manner',
    'urdu', 'relies', 'consists', 'today', 'tomorrow', 'region', 'challenging', 'faulty',
    'percentile', 'places', 'subscribers', 'subscriber', 'spouse', 'plays', 'helpful',
    'weeks', 'presented', 'separately', 'segregate', 'integrates', 'japanese', 'paths',
    'christmas', 'concentration', 'closer', 'avoids', 'wedding', 'cgpa',
    'constantly', 'desirable employers', ' intersections', ' reality',
    'thousands', 'work', 'eye', 'interests', 'long drives', ' description',
    'married', 'birth', 'marathi', 'extracted', 'time', ' keeping', 'problem',
    'running', 'cycling', 'listening', 'movies', 'music', 'abilities', 'good knowledge',
    'called', 'india', 'utilize', 'skill', 'status', 'unauthorised', 'appreciations',
    'join', 'now', 'mail', 'phone', 'email', 'email:', 'total',
    'tel', 'skills:', 'skills', 'looking', 'ctc', 'ctc:', 'career', 'highly',
    'salary', 'salary:', 'address', 'address:', 'responsibility', 'responsibilities',
    'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december',
    'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec',
    'roles', 'no.:', 'no.', "able", "about", "above", "abroad", "according", "accordingly", "across", "actually", "adj", "after",
    "afterwards", "again", "against", "ago", "ahead", "ain't", "all", "allow", "allows", "almost", "alone", "along",
    "alongside", "already", "also", "although", "always", "am", "amid", "amidst", "among", "amongst", "an", "and",
    "another", "any", "anybody", "anyhow", "anyone", "anything", "anyway", "anyways", "anywhere", "apart", "appear",
    "appreciate", "appropriate", "are", "aren't", "around", "as", "a's", "aside", "ask", "asking", "associated",
    "at", "available", "away", "awfully", "back", "backward", "backwards", "be", "became", "because", "become",
    "becomes", "becoming", "been", "before", "beforehand", "begin", "behind", "being", "believe", "below", "beside",
    "besides", "best", "better", "between", "beyond", "both", "brief", "but", "by", "came", "can", "cannot", "cant",
    "can't", "caption", "cause", "causes", "certain", "certainly", "changes", "clearly", "c'mon", "co", "co.", "com",
    "come", "comes", "concerning", "consequently", "consider", "considering", "contain", "containing", "contains",
    "corresponding", "could", "couldn't", "course", "c's", "currently", "dare", "daren't", "definitely", "described",
    "despite", "did", "didn't", "different", "directly", "do", "does", "doesn't", "doing", "done", "don't", "down",
    "downwards", "during", "each", "edu", "eg", "eight", "eighty", "either", "else", "elsewhere", "end", "ending",
    "enough", "entirely", "especially", "et", "etc", "even", "ever", "evermore", "every", "everybody", "everyone",
    "everything", "everywhere", "ex", "exactly", "example", "except", "fairly", "far", "farther", "few", "fewer",
    "fifth", "first", "five", "followed", "following", "follows", "for", "forever", "former", "formerly", "forth",
    "forward", "found", "four", "from", "further", "furthermore", "get", "gets", "getting", "given", "gives",
    "goes", "going", "gone", "got", "gotten", "greetings", "had", "hadn't", "half", "happens", "hardly", "has",
    "hasn't", "have", "haven't", "having", "he", "he'd", "he'll", "hello", "help", "hence", "her", "here",
    "hereafter", "hereby", "herein", "here's", "hereupon", "hers", "herself", "he's", "hi", "him", "tasked", "himself", "his",
    "hither", "hopefully", "how", "howbeit", "however", "hundred", "i'd", "ie", "if", "ignored", "i'll", "i'm",
    "immediate", "in", "inasmuch", "inc", "inc.", "indeed", "indicate", "indicated", "indicates", "inner", "inside",
    "insofar", "instead", "into", "inward", "is", "isn't", "it", "it'd", "it'll", "its", "it's", "itself", "i've",
    "just", "k", "keep", "keeps", "kept", "know", "known", "knows", "last", "lately", "later", "latter", "latterly",
    "least", "less", "lest", "let", "let's", "like", "liked", "likely", "likewise", "little", "look", "looking",
    "looks", "low", "lower", "ltd", "made", "mainly", "make", "makes", "many", "may", "maybe", "mayn't", "me",
    "mean", "meantime", "meanwhile", "merely", "might", "mightn't", "mine", "minus", "miss", "more", "moreover",
    "most", "mostly", "mr", "mrs", "much", "must", "mustn't", "my", "myself", "name", "namely", "nd", "near",
    "nearly", "necessary", "need", "needn't", "needs", "neither", "never", "neverf", "neverless", "nevertheless",
    "new", "next", "nine", "ninety", "no", "nobody", "non", "none", "nonetheless", "noone", "no-one", "nor",
    "normally", "not", "nothing", "notwithstanding", "novel", "now", "nowhere", "obviously", "of", "off", "often",
    "oh", "ok", "okay", "old", "on", "once", "one", "ones", "one's", "only", "onto", "opposite", "or", "other",
    "others", "otherwise", "ought", "oughtn't", "our", "ours", "ourselves", "out", "outside", "over", "overall",
    "own", "particular", "particularly", "past", "per", "perhaps", "placed", "please", "plus", "possible",
    "presumably", "probably", "provided", "provides", "que", "quite", "qv", "rather", "rd", "re", "really",
    "reasonably", "recent", "recently", "regarding", "regardless", "regards", "relatively", "respectively", "right",
    "round", "said", "same", "saw", "say", "saying", "says", "second", "secondly", "see", "seeing", "seem", "seemed",
    "seeming", "seems", "seen", "self", "selves", "sensible", "sent", "serious", "seriously", "seven", "several",
    "shall", "shan't", "she", "she'd", "she'll", "she's", "should", "shouldn't", "since", "six", "so", "some",
    "somebody", "someday", "somehow", "someone", "something", "sometime", "sometimes", "somewhat", "somewhere",
    "soon", "sorry", "specified", "specify", "specifying", "still", "sub", "such", "sup", "sure", "take", "taken",
    "taking", "tell", "tends", "th", "than", "thank", "thanks", "thanx", "that", "that'll", "thats", "that's",
    "that've", "the", "their", "theirs", "them", "themselves", "then", "thence", "there", "thereafter", "thereby",
    "there'd", "therefore", "therein", "there'll", "there're", "theres", "there's", "thereupon", "there've", "these",
    "they", "they'd", "they'll", "they're", "they've", "thing", "things", "think", "third", "thirty", "this",
    "thorough", "thoroughly", "those", "though", "three", "through", "throughout", "thru", "thus", "till", "to",
    "together", "too", "took", "toward", "towards", "tried", "tries", "truly", "try", "trying", "t's", "twice",
    "two", "un", "under", "underneath", "undoing", "unfortunately", "unless", "unlike", "unlikely", "until", "unto",
    "up", "upon", "upwards", "us", "use", "used", "useful", "uses", "using", "usually", "v", "value", "various",
    "versus", "very", "via", "viz", "vs", "want", "wants", "was", "wasn't", "way", "we", "we'd", "welcome", "well",
    "we'll", "went", "were", "we're", "weren't", "we've", "what", "whatever", "what'll", "what's", "what've", "when",
    "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "where's", "whereupon", "wherever",
    "whether", "which", "whichever", "while", "whilst", "whither", "who", "who'd", "whoever", "whole", "who'll",
    "whom", "whomever", "who's", "whose", "why", "will", "willing", "wish", "with", "within", "without", "wonder",
    "won't", "would", "wouldn't", "yes", "yet", "you", "you'd", "you'll", "your", "you're", "yours", "yourself",
    "yourselves", "you've", "zero", "a", "how's", "i", "when's", "why's", "b", "c", "d", "e", "f", "g", "h", "j",
    "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "uucp", "w", "x", "y", "z", "I", "www", "amount", "bill",
    "bottom", "call", "computer", "con", "couldnt", "cry", "de", "describe", "detail", "due", "eleven", "empty",
    "fifteen", "fifty", "fill", "find", "fire", "forty", "front", "full", "give", "hasnt", "herse", "himse",
    "interest", "itseâ€", "mill", "move", "myseâ€", "part", "put", "show", "side", "sincere", "sixty", "system",
    "ten", "thick", "thin", "top", "twelve", "twenty", "abst", "accordance", "act", "added", "adopted", "affected",
    "affecting", "affects", "ah", "announce", "anymore", "apparently", "approximately", "aren", "arent", "arise",
    "auth", "beginning", "beginnings", "begins", "biol", "briefly", "ca", "date", "ed", "effect", "et-al", "ff",
    "fix", "gave", "giving", "heres", "hes", "hid", "home", "id", "im", "immediately", "importance", "important",
    "index", "information", "invention", "itd", "keys", "kg", "km", "largely", "lets", "line", "'ll", "means", "mg",
    "million", "mug", "na", "nay", "necessarily", "nos", "noted", "obtain", "obtained", "omitted", "ord", "grow", "key"
    "owing", "page", "pages", "poorly", "possibly", "potentially", "pp", "predominantly", "present", "previously",
    "primarily", "promptly", "proud", "quickly", "ran", "readily", "ref", "refs", "related", "research", "resulted",
    "resulting", "results", "run", "sec", "section", "shed", "shes", "showed", "shown", "showns", "shows",
    "significant", "significantly", "similar", "similarly", "slightly", "somethan", "specifically", "state",
    "states", "stop", "strongly", "substantially", "sufficiently", "suggest", "thered", "thereof",
    "therere", "thereto", "theyd", "theyre", "thou", "thoughh", "thousand", "throug", "til", "tip", "ts", "ups",
    "usefully", "usefulness", "'ve", "vol", "vols", "wed", "whats", "wheres", "whim", "whod", "whos", "widely",
    "words", "world", "youd", "youre", 'male', 'female', 'other'
    'town', 'company', 'city', 'organisation', 'developed', 'projects',
    'develop', 'qualification', 'qualifications', 'mentioned  marital  status',
    'mentioned',  'marital', 'personal  details', 'details  personal', 'attached  resume',
    'months', 'month', 'year', 'years', 'mentioned  gender', 'gender',
    'mentioned  physically  challenged', 'mentioned  highest  degree', 'mentioned',
    'mentioned  expected', 'responsible', 'month  description', 'job', 'details', 'job', 'type'
    'ends', 'subsidiary', 'marks', 'couple', 'day', 'relate', 'key', 'spend'
]
